### ISSUE TITLE
Using trimmed DLog keys doesn't work for Darlin proving system

### ISSUE THREAD

**Issue by ptagl** [HorizenOfficial/zendoo-mc-cryptolib#59] opened 2022-05-16 09:05 UTC
It seems that the latest version of CCTP Lib, that removed the possibility to initialize the DLog keys several time at runtime, makes the MC Crypto Lib to fail some unit tests. See [this comment](https://github.com/HorizenOfficial/zendoo-mc-cryptolib/pull/58#issuecomment-1126172056) for further details.

As a brief description:

1. Generate small DLog Keys (2^9 segment size) and generate proving and verification keys
2. Generate large DLog keys (2^18 segment size) and try to generate a proof with the proving key of the last step using the small segment size (2^9) so that the DLog keys get trimmed
3. Generate large DLog keys (2^18 segment size) and try to verify the generated proof with the verification key from step 1

These steps work correctly when using `Coboundary Marlin`, while we get an error during the proof generation at step 2 for `Darlin`.

The behavior can be reproduced by launching the unit test in the `mcTest` folder on the branch pointed by #58.

**Comment by DanieleDiBenedetto** [comment] 2022-06-16 15:20
@i-Alex in reality it's a different issue here (also involving DLOG keys, these objects are very delicate :D)

**Comment by DanieleDiBenedetto** [comment] 2022-09-28 08:39
The issue is due to an error fixed in https://github.com/HorizenOfficial/zendoo-mc-cryptolib/commit/540fe8b0d8fd6d072ea82588c6830d4237198ed0 as the segment_size parameter was not passed to the `generate_params` function from the `create_test_cert_proof `and `create_test_csw_proof` functions

**Closed by DanieleDiBenedetto** 2022-09-28 08:39 UTC
